"""兼容模块 — 从本地 candela.py 中导入公共类型

candela.py 是 xsdata 自动生成的 XML 绑定模型，V2 自带一份副本，不依赖 V1。
"""
from .models.candela import (
    Candela,
    Name,
    Desc,
    Tuv,
    Comp,
    Excl,
    Textmap,
    Text,
    # Candela 原始类型（用于转换器匹配）
    Ecu,
    Diagclass,
    Diaginst,
    Protocolservice,
    Constcomp,
    Staticcomp,
    Simpleproxycomp,
    Statusdtcproxycomp,
    Contentcomp,
    Eositercomp,
    Domaindataproxycomp,
    Groupofdtcproxycomp,
    Numitercomp,
    Muxcomp,
    Muxcompcont,
    Dataobj,
    Diddataref,
    Didref,
    Did,
    Gapdataobj,
    Godtcdataobj,
    Recorddataobj,
    Specdataobj,
    Simplecompcont,
    Texttbl,
    Lincomp,
    Ident,
    Muxdt,
    Recorddt,
    Structdt,
    Structure,
    Struct,
    Case,
    Req,
    Dcltmpl,
    Dclsrvtmpl,
    Shstatic,
    Shproxy,
    Negrescode,
    Service,
    Staticvalue,
)
